### ISSUE TITLE
Cross Platform build script: Resolved, look inside

### ISSUE THREAD

**Issue by elico** [andybalholm/redwood#11]
I wrote a nice script that build the binary for:
windows
linux's(arm included)
BSD's
Solaris
Darwin

Can we somehow pull it into the repo?
Or should I will post it is a gist?

**Comment by andybalholm** [comment]
If we put it in the repo, people might think they need the script in order to build Redwood.

**Comment by elico** [comment]
@andybalholm Then we can add it into a seperate "tools" or "scripts" directory.
Most of these who have the understanding how to compile a software with GoLang would not be "non-smart" enough to figure such a thing(to my understanding).
And we can always add a README.md file into the "tools" directory that will explain what it's for.
The other option is to attach a gist with the scripts to this issue.
Let me know what is better to your understanding from the realitstic options.

**Comment by andybalholm** [comment]
I'll vote for the gist.

**Comment by elico** [comment]
OK gist it is:
https://gist.github.com/elico/7e0da9efef044f8c21714f830ae5b4e2

just add these files into the redwood directory, run "make update", then "make all".
The result would be a ./bin/ directory with a bunch of portable binaries for linux windows and couple others.(leave the issue open so it would be visible)

**Comment by elico** [comment]
@andybalholm I have seen that a go.mod file was added.
Can it affect the way I am building redwood?

**Comment by andybalholm** [comment]
It potentially could. I don't have a lot of experience with Go modules yet, so I'm not sure.

**Comment by elico** [comment]
@andybalholm Resolved.
