### ISSUE TITLE
How do I define ssl-bump exception rules for a big set of domains?

### ISSUE THREAD

**Issue by elico** [andybalholm/redwood#13]
In squid I have the option to use regex for a single domain or multiple ie .microsoft.com will take both microsoft.com and all the subdomains.
And the destination IP is acl is missing for me, is it possible to add in some way an option for that?
Is the there such an option in RedWood?
(I am willing to put some efforts into it)

**Comment by thinkwelltwd** [comment]
> In squid I have the option to use regex for a single domain or multiple ie .microsoft.com will take both microsoft.com and all the subdomains.

microsoft.com will automatically match all subdomains.  The dot prefix is not necessary. If all subdomains is too broad, you can assign a negative score to the subdomains that shouldn't be bumped.


```
default 1000
microsoft.com
games.microsoft.com -1000 # sslbump this subdomain
```

For IPs, just enter an IP address into the ssl-bump exception list.

```
default 1000
microsoft.com
games.microsoft.com -1000 # sslbump this subdomain
104.40.211.35
```

**Comment by elico** [comment]
@thinkwelltwd I want to add a cidr..(/8./12,/16)

**Comment by andybalholm** [comment]
Use a regex:

    /^104\.40\.211\./h

**Comment by elico** [comment]
@andybalholm is there a negate rule? I was sure there is.
my acls.conf looks like this:
```
acl localnet user-ip 192.168.0.0/16 10.0.0.0/8 172.16.0.0/12
acl all user-ip 0.0.0.0/0
acl nobump url /10\./h
allow nobump
ssl-bump localnet
allow localnet
block all
#disable-proxy-headers all
```
I want to negate the ssl-bump for specic urls or a cidr.
The README.md describes a "negate" option but not how to use it.
what I tried is:
```
acl localnet user-ip 192.168.0.0/16 10.0.0.0/8 172.16.0.0/12
acl all user-ip 0.0.0.0/0 
acl nobump url /10\./h
allow localnet nobump
ssl-bump localnet !nobump
allow localnet
block all
#disable-proxy-headers all
```
and the result is(access.log)
2017-03-11 11:58:40,192.168.89.58,ssl-bump,http://10.0.0.138:443,CONNECT,0,,0,,,,localnet !nobump,,,,HTTP/1.1,,Windows
2017-03-11 11:58:41,192.168.89.58,allow,https://10.0.0.138/lib/1477395035/js/core.min.js,GET,200,application/javascript,756416,,,,localnet,,,,HTTP/2.0,,Windows

So it's a bit weird. it matches the nobump negate rule and bumps?

**Comment by andybalholm** [comment]
ACL URL rules don't support regular expressions.

**Comment by elico** [comment]
@andybalholm so I didn't understood the documentation:
```
url
The URL requested. (This matches the same way as regular URL matching rules.)
```
What does it mean?
Where can I define an exception of address in the form of domains or regualar expressions from being bumped?

**Comment by thinkwelltwd** [comment]
> Where can I define an exception of address in the form of domains or regualar expressions from being bumped?

That's a category. Categories are a type of ACL in Redwood.

In redwood.conf, you'll have a directory path.
`categories /etc/redwood/categories`

Create an sslbypass directory `/etc/redwood/categories/sslbypass`, with the following files:

category.conf
```
description: Sites to CONNECT directly
action: ignore
```
sslbypass.list

```
# sslbypass score must be the highest scoring category on the REQUEST
default 1000
microsoft.com
games.microsoft.com -1000 # sslbump this subdomain
104.40.211.35
/^104\.40\.211\./h
```

In redwood.conf, you'll have these lines:

```
acl connect method CONNECT
allow connect sslbypass
ignore-category connect
ssl-bump connect
```

You now have a list of domain & regex rules that won't be bumped. Everything else will be bumped that is not in the sslbypass category.

**Comment by elico** [comment]
@thinkwelltwd thanks!!
Works like a charm.
Here we come RPM packages of RedWood :D I am planning to publish these in the comming week.
