### ISSUE TITLE
Integration of drbl-peer into redwod

### ISSUE THREAD

**Issue by elico** [andybalholm/redwood#14]
Hey,
I wrote https://github.com/elico/drbl-peer and I wanted to add redwood support for it.
I can try to contributre the coding for it via a fork and then a pull requet but I will need coupel pointers.
The basic setup is based on a single text file which will contain the relevenat details.
The caching can be done using a caching DNS server and\or an http caching proxy so there is no need to implement caching of results inside redwood.

I think that a simple "if file exists" then "use" the function with the file settings would be the most apropriate.
The drbl peers list can be contain a custom DB or a publicone like OpenDNS or Symantec.

**Comment by andybalholm** [comment]
What do you need pointers on? How to set up the config? I would recommend that for each list you set up, you should be able to select a category and a score. If the domain is on the list, it would score that much in that category.

**Comment by elico** [comment]
@andybalholm by each list you do you mean each RBL? server? peerslist.txt file?
Currently the library implemets https://godoc.org/github.com/elico/drbl-peer#DrblPeers.Check
which checks each list until there is a first weight hit or end of the list and return as false and the weight.
So I can use just send the host to the check function and it will return either a false or true eventually for a match.
I need the vectoring points in redwood code which I can insert this test and what I need is only the hostname of the request.
The config should be pretty simple: you can define one drbl per server and use some kind of acl to verify who this drbl check applies to.
it can be either a src ip or domains or something else.

**Comment by andybalholm** [comment]
(I have not really looked at your code, or figured out what kind of servers it supports.)

Looking at your API, it looks like you can define some kind (or various kinds) of remotely-maintained lists of domains, potentially with weights. We need to map the domain's presence on a list, and it's weight, to a score in a Redwood category. I think a category is better than an ACL, since you can weight it, and override it with a higher-scoring category.

**Comment by elico** [comment]
@andybalholm  I will look into it again in about 24-48 hours and then I will try to see how and why.
Thanks until now.

**Comment by elico** [comment]
@andybalholm I was thinking about it and a category is good but I there are two scenarios with my library.
For now it's only testing for a hostname but I might want later to add a test for the souce IP.
Tommorow I will sit on the code to see how the categories are being parsed.
I think that adding a unique file for a category would be the right way and in the case such a "drblpeers.xyz" file exists it will be parsed and be tested at  specific verctor points.

**Comment by andybalholm** [comment]
You can use ACLs to block a category for certain IP addresses and not others.

**Comment by elico** [comment]
@andybalholm but not dynamically, right?

**Comment by andybalholm** [comment]
What do you mean by dynamically? Are you trying to build an interface to outsource all of Redwood's access control logic to an external program? I had assumed the DRBL server would just be classifying sites, not determining policy.

**Comment by elico** [comment]
@andybalholm drbl is to classify sites but...
There are couple types of types "dns" "dnsbl" "http" and I might add others.
My curret will is to allow RedWood be extended by a dynamic BL which can be changed at will.
My main peers are OpenDNS, Symantec and SquidBlocker which I wrote.
If I will understand RedWood code enough I might think about adding an extention to a radius server query for larger deployments.

**Comment by andybalholm** [comment]
So the blacklist is dynamic, but its relationship to the source IPs is not, right? So once we make a way to have dynamic categories, the categories can be blocked or allowed for certain source IPs with ACLs.  (Did you know that you can reference a category name in an ACL action line?)

**Comment by elico** [comment]
@andybalholm right.
I didn't knew that but @thinkwelltwd helped me to realize this.

**Comment by spikedrba** [comment]
hi, incredible that I hadn't come across redwood before, looks awesome. I'm not sure if this is the appropriate place for it, but I'm considering switching to redwood for this exact type of feature since simple keyword based categorization ime doesn't work well enough (that's what I've been doing for several years and complaints just kept pouring in).
Most paid cf services will rely on 3rd party providers who run crawlers and beefy ML farms to build categorization trees, one example being untangle using zvelo. All these services basically analyze the page and then map it to a IAB Taxonomy and offer that through an API. From my initial assessment this is more effective than keyword matching and rbls, which far too often tend to be outdated.

what are your thoughts on implementing something like this?

thank you

**Comment by elico** [comment]
@spikedrba I read your post couple times and wasn't sure about what you are refereeing to "something like this"?
What service or tool did you had in mind?

**Comment by andybalholm** [comment]
@elico I think he meant "something that connects Redwood to a third-party classifier service."

@spikedrba I think the way to do it would be that each classification from the external classifier would be mapped to points in one or more Redwood categories. I'm not really interested in implementing something like that myself, but you are welcome to do it, and I might be able to give you some pointers along the way.

**Comment by spikedrba** [comment]
@elico what @andybalholm said, something that allows Redwood to call out to a third-party service to classify the url (or even potentially deny it, which is what ICAP services are all about and how most cf appliances are implemented).

@andybalholm thank you for your feedback, I can totally understand that this isn't aligned with your priorities. That said, is what I'm talking about different than the drbl-peer solution @elico is interested into? in other words would the way you'd recommend him to plug that in different than the way I'd plug in an external classifier?

thanks,

**Comment by andybalholm** [comment]
They are basically the same; a classification service just provides richer data than a DRBL. So I think a similar approach would work.

**Comment by elico** [comment]
@andybalholm it will take me time to integrate the solution due to happy things in life.
