### ISSUE TITLE
Yahoo.com stylesheets not loading...Is this a proxy issue?

### ISSUE THREAD

**Issue by fifthsegment** [andybalholm/redwood#15]
I'm getting a 400 error on all stylesheets when opening http://www.yahoo.com. The website opens fine without Redwood, have any of you guys experienced the same?

**Comment by thinkwelltwd** [comment]
Please post some logging data. Relevant lines from access.log, errors.log, and tls.log would be most helpful.

**Comment by elico** [comment]
@fifthsegment I am using redwood and https://www.yahoo.com works fine for me.
