### ISSUE TITLE
Exclude some Https sites from ssl_bump

### ISSUE THREAD

**Issue by test1964** [andybalholm/redwood#20]
Hi,

There is some issue in "acl config"  file that not working.
When I try this(in acl.conf):

acl connect method CONNECT
acl nobump url dk.com
ssl-bump connect !nobump

all working well(got  dk.com real certificate)

But this not working:

acl connect method CONNECT
acl nobump url   /dk/h
ssl-bump connect !nobump

Why can't use Url regular expressions?
How can I put sites tjat need to exclude from ssl-bump in some list file in categories dir(I try it without success)?

**Comment by andybalholm** [comment]
The `url` ACL type is only for literal URLs. I've thought about adding something like `url-regex`, but I have not gotten it done. It's not very urgent, because you can use categories in ACLs.

So, did you make a category called "nobump" and put that regex in it with a whole lot of points?

**Comment by test1964** [comment]
I checked with category and with regex and seem to work well, But now face  another problem
that all rules in this category also effect for regular surfing url rules, I want that nobump rules will be only for ssl-bump (for example when I put rule like "/dk/h" I do not want to open all dk sites - only the certifecate of dk.com), How to do it?

**Comment by andybalholm** [comment]
Set the category's default action to `ignore`, and use an ACL line to allow it on CONNECT requests.

**Comment by test1964** [comment]
I fix as you said and have access to sites even it in block.
acls.conf
---------
acl connect method CONNECT
allow connect nobump
ssl-bump connect !nobump


nobump/category.conf
-------------------------
action: ignore

nobump/sites.list
-------------------
default 2500
/dk/h

* this works well and got dk cert 
now I add this:

blocksites/category.conf
---------------------------
action: block

blocksites/sites.list
--------------------
default 1000
dk.com

* and still I can surf to dk.com site (even I try to block it), why?

**Comment by andybalholm** [comment]
If you "allow" the CONNECT request, you allow all the data that passes through that connection. You can't filter a site without SSLBumping it.

**Comment by test1964** [comment]
Then how to to exclude  a certificate in ssl-bump thru  category files with points but make disable it for 
surfing filtering.(In my example I want all sites with dk on hostname will get real certificate and still to block dk.com)?

**Comment by thinkwelltwd** [comment]
nobump.list:

```
default 2500
/dk/h
dk.com -2500
```

**Comment by test1964** [comment]
Thanks
