### ISSUE TITLE
Redwood service stop after some time

### ISSUE THREAD

**Issue by test1964** [andybalholm/redwood#22]
Hey ,

I try to check the Redwood filter in port 80 only in transparent mode with heavy traffic (centos 7 ).
After some time (20 min) I get this in my messages log:
systemd: redwood.service: main process exited, code=exited, status=2/INVALIDARGUMENT
systemd: Unit redwood.service entered failed state.
systemd: redwood.service failed.

And if I try to restart again it fails, Why?

**Comment by test1964** [comment]
I also added log to file to cache the  problem and got this:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x474e51]

goroutine 577556 [running]:
bufio.(*Writer).WriteString(0x0, 0x9bace1, 0x19, 0xc4270a3b00, 0xc421284ae0, 0x0)
        /usr/local/go/src/bufio/bufio.go:664 +0x41
net/http.(*expectContinueReader).Read(0xc424cec560, 0xc42bcc0000, 0x140, 0x1000, 0x9255e0, 0x42b301, 0x0)
        /usr/local/go/src/net/http/server.go:857 +0x16a
io.(*LimitedReader).Read(0xc420812a20, 0xc42bcc0000, 0x1000, 0x1000, 0x0, 0xc4284d4000, 0xc424ad1ba0)
        /usr/local/go/src/io/io.go:436 +0x6c
bufio.(*Writer).ReadFrom(0xc4262f6a40, 0xc5d960, 0xc420812a20, 0x7f1866d00110, 0xc4262f6a40, 0x1)
        /usr/local/go/src/bufio/bufio.go:696 +0xcd
io.copyBuffer(0xc5cfe0, 0xc4262f6a40, 0xc5d960, 0xc420812a20, 0x0, 0x0, 0x0, 0x929ae0, 0xc4262f6c01, 0xc420812a20)
        /usr/local/go/src/io/io.go:384 +0x2cb
io.Copy(0xc5cfe0, 0xc4262f6a40, 0xc5d960, 0xc420812a20, 0x0, 0xc4270a33e0, 0x68e06f)
        /usr/local/go/src/io/io.go:360 +0x68
net/http.(*transferWriter).WriteBody(0xc425c6f880, 0xc5cfe0, 0xc4262f6a40, 0x2, 0x2)
        /usr/local/go/src/net/http/transfer.go:319 +0x675
net/http.(*Request).write(0xc42133ce00, 0xc5cfe0, 0xc4262f6a40, 0xc420016000, 0xc428703050, 0xc4293ef380, 0x0, 0x0)
        /usr/local/go/src/net/http/request.go:622 +0x6e9
net/http.(*persistConn).writeLoop(0xc420fe10e0)
        /usr/local/go/src/net/http/transport.go:1707 +0x1ad
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1118 +0xa5a



Hope this can give some info about the problem.

* Btw Go version is   go1.8

**Comment by elico** [comment]
@test1964 it could be a golang bug or a panic that crashes the server.
I cannot say which and I will wait for @andybalholm to try and answer

**Comment by andybalholm** [comment]
What revision were you using?

**Comment by test1964** [comment]
The version without last fix ( Apr 21, 2017).

**Comment by elico** [comment]
@test1964 transparent or a simple forward proxy?

**Comment by test1964** [comment]
transparent  and only port 80

**Comment by andybalholm** [comment]
I'm guessing that an unusual client (something other than a browser) is triggering a bug in the http package's support for Expect: Continue. That's a somewhat obscure feature, so the likelihood of bugs there is higher than average. It would be great if you could figure out what client request was triggering this.

Also try rebuilding with Go 1.8.1, in case any of the bug fixes there helps.

**Comment by test1964** [comment]
Spoke with @elico and after added:
-close-idle-connections 15m0s 
Redwood was stable again without any problems.(using 1 min crash it after 30 min)
