### ISSUE TITLE
content pruning example

### ISSUE THREAD

**Issue by stern0m1** [andybalholm/redwood#24]
Hi,
I am having trouble getting content pruning working.
I dont think the examples in the readme are still relevant.
If you can give me a current example of content pruning would be greatly appreciated.
Thanks

**Comment by thinkwelltwd** [comment]
It would be much better if you would post examples that aren't working.

**Comment by stern0m1** [comment]
I am really a newbie so I thought a working example would be more prudent for me. :) I may be be missing something simple.
Anyways for testing I tried:
in pruning.conf:
osimagefilter.org div.test 

Doesnt work for me.

Thanks

**Comment by thinkwelltwd** [comment]
>I may be be missing something simple.

Yes you are! ;-) That page contains no div with a class of `test`, so there's none to prune out.  But if you want to prune the div with the ID of `test`, use:

```osimagefilter.org div#test```

**Comment by stern0m1** [comment]
Hi,
osimagefilter.org div#test doesnt work by me either.
I have in redwood.conf
content-pruning /etc/redwood/pruning.conf
Any ideas where I could be going wrong?
I do see osimagefilter.org in the logs.

BTW my goes is eventually use redwood to inject js. Do you see any issues with that?
I want to build this chrome extension in a router...
https://chrome.google.com/webstore/detail/os-image-filter/digkbjcglmbbipijiogdeegbfbepgdon

Thanks!

**Comment by thinkwelltwd** [comment]
> osimagefilter.org div#test doesnt work by me either.

Did you reload the Redwood process? 

If so, then it's time to post pastebin links to your config files. Because the documentation is correct.

**Comment by stern0m1** [comment]
Yes I reloaded redwood.
[pruning.conf.txt](https://github.com/andybalholm/redwood/files/1344415/pruning.conf.txt)
[redwood.conf.txt](https://github.com/andybalholm/redwood/files/1344418/redwood.conf.txt)
Thanks!

**Comment by thinkwelltwd** [comment]
Ok, thanks for that. Post the _entire_ output of

`redwood -test osimagefilter.org`

**Comment by stern0m1** [comment]
[root@localhost ~]# redwood -test osimagefilter.org
URL: http://osimagefilter.org

No URL rules match.

No ACL rule was triggered.

Downloading content...
200 OK

No ACL rule was triggered.

Just to clarify, its probably something very simple im missing... I am by means an expert in these matters:)

Thanks!

**Comment by andybalholm** [comment]
What's in acls.conf? In particular, does it enable phrase-scan? Pruning only works on pages that are phrase-scanned.

**Comment by stern0m1** [comment]
Ok. so thats my problem. I didnt realize that. Ill have to study the docs and enable phrase-scan.

I understand the docs mentions phrase-scan by content pruning but it wasn't clear to me that its a requirement.

Thanks

**Comment by stern0m1** [comment]
If you/someone could post example conf files that would be helpful and I would greatly appreciate it.
I think others may benefit also.

Thanks

**Comment by andybalholm** [comment]
Have you looked at https://github.com/andybalholm/redwood-config

**Comment by stern0m1** [comment]
My opologies I didn't notice. Will look. Thanks




On Fri, Sep 29, 2017 at 3:48 PM -0400, "Andy Balholm" <notifications@github.com> wrote:










Have you looked at https://github.com/andybalholm/redwood-config
