### ISSUE TITLE
Content injection

### ISSUE THREAD

**Issue by stern0m1** [andybalholm/redwood#25]
Hi,
I'm thinking about adding content injection to this project. I am wondering if there is any technical reasons why the author don't include content injection or is it just not within the authors use case?

Thanks

**Comment by andybalholm** [comment]
It isn't something we've run into a need for. It should be possible to add it; it shouldn't be much different from content pruning.

**Comment by unixabg** [comment]
Greetings,
I believe this would be a valuable feature.

**Comment by thinkwelltwd** [comment]
>  I believe this would be a valuable feature.

Valuable for...what? Features aren't usually developed in a vacuum; they have to scratch an itch. So it'd be helpful if you'd provide use-cases, and better yet, PRs.

**Comment by stern0m1** [comment]
My use case is, to filter inappropriate areas of images.  That means specfic areas of the images are grayed out. I need to replace the images as apposed to just pruning  I would like for the actual processing to be done on the end users machine. Henceforth I would like to inject js that would do the processing.




I have done this already as a chrome extension, not I want to implement it in cheap routers.




Regards




On Mon, Oct 2, 2017 at 12:34 PM -0400, "Dave Burkholder" <notifications@github.com> wrote:













I believe this would be a valuable feature.



Valuable for...what? Features aren't usually developed in a vacuum; they have to scratch an itch. So it'd be helpful if you'd provide use-cases, and better yet, PRs.

**Comment by unixabg** [comment]
Greetings,

I will reply inline.

On Mon, Oct 2, 2017 at 11:34 AM, Dave Burkholder <notifications@github.com>
wrote:

> I believe this would be a valuable feature.
>
> Valuable for...what?
>
Hmm, fwiw your question seems to carry an odd grammatical tone, anyhow,
presentation layer control.


> Features aren't usually developed in a vacuum; they have to scratch an
> itch. So it'd be helpful if you'd provide use-cases, and better yet, PRs.
>
I do not understand your reference of "PRs", so to that I can not comment.
Please allow me to just address the statement of use-cases as a redwood
user with only a small subset of possible use cases:

1.) Injecting a small filtered icon when a word match is found to provide
the user the balance of the text and not just block based on weight.

2.) Injecting diagnostics or even a count meter in page for the user.

3.) Injecting the ability to reveal words or grayed out content with a
password url.

4.) Injecting code to leverage weighting system and add a pop-up "Attention
you are on company equipment, please make good choices." when you are at
some percentage of page constituting a block.

I believe the feature request would fully empower the redwood admin to have
complete control over the presentation layer.

**Comment by stern0m1** [comment]
Here's a first attempt at modifying redwood for content injection.
https://github.com/kazan1000/redwood
(Its not me, someone I got to do it.)

**Comment by thinkwelltwd** [comment]
>  Hmm, fwiw your question seems to carry an odd grammatical tone, anyhow,
presentation layer control.

I suppose the question was rather abbreviated; I meant to be asking for some examples of _how_ content injection would be a useful feature, which you've now provided. 

>I do not understand your reference of "PRs", 

I was referring to [Github Pull Requests](https://help.github.com/articles/about-pull-requests/).

Regarding the suggested possible uses of content injection, I can see why some of those features might be desired. However, none of them rely solely on content injection, and all would require internal changes to  produce the data to be injected.

Regarding example number one, are you wanting a block mode that blocks images on the page, but allows the full page text?

Regarding example number 2, wouldn't a report engine analying access.log provide this data just as well? Is there some reason it needs to be real-time?

Regarding example number 4, "when you are at some percentage of page constituting a block" presents a block page to the user.  Messages can be could displayed to the user on this page.  Pruning is not blocking; that's removing an item from the page.

> Here's a first attempt at modifying redwood for content injection.

Could you have kazan1000 fork this repo so code changes can be submitted via pull requests?

**Comment by unixabg** [comment]
Greetings,

On Tue, Oct 3, 2017 at 6:43 AM, Dave Burkholder <notifications@github.com>
wrote:

> Hmm, fwiw your question seems to carry an odd grammatical tone, anyhow,
> presentation layer control.
>
> I suppose the question was rather abbreviated; I meant to be asking for
> some examples of *how* content injection would be a useful feature, which
> you've now provided.
>

ack and no worries.

I do not understand your reference of "PRs",
>
> I was referring to Github Pull Requests
> <https://help.github.com/articles/about-pull-requests/>.
>

Ahh yes that would make sense.


> Regarding the suggested possible uses of content injection, I can see why
> some of those features might be desired. However, none of them rely solely
> on content injection, and all would require internal changes to produce the
> data to be injected.
>

On this I have not had the time to look at the code, currently swamped at
work, so you may be entirely correct here.

Regarding example number one, are you wanting a block mode that blocks
> images on the page, but allows the full page text?
>

I think block mode is not what I would describe it as, I would call it and
injection based on regex pattern s/_match/_replace/g operation. So sort of
washing the page of things with a preferred placeholder. And should the
page normally be blocked then so be it, but imagine just one or two (or
some small n) occurrences of  _match being washed with _replace. I believe
this simple model can all the injection that would be needed.


> Regarding example number 2, wouldn't a report engine analying access.log
> provide this data just as well? Is there some reason it needs to be
> real-time?
>
This example was selfish and probably to concrete, but sometimes could be
helpful if you could provide a visual safe status for the user so they
could be empowered to make good choices.



> Regarding example number 4, "when you are at some percentage of page
> constituting a block" presents a block page to the user.
>
If I understand what you saying here, I would say do not block if weight
has not been reached, but let's say at 50% or some percent (and this I
suppose could all be done on the browser, if redwood could share a term
list and inject the javascript), then regex against the close </html> and
put in some javascript to inform the users + </html> to send the
warning/information message to the user. Or so I think that would work,
untested atm.


> Messages can be could displayed to the user on this page. Pruning is not
> blocking; that's removing an item from the page.
>
I like this idea, that does seem to go along with the injection idea.

Here's a first attempt at modifying redwood for content injection.
>
> Could you have kazan1000 fork this repo so code changes can be submitted
> via pull requests?
>

kazan1000 first thank you for your contribution. kazan1000 if you are
reading, it would be very helpful to all if we could get you to fork this
git of redwood and apply your changes in a way to create a pull request. I
believe the correct order to do that so everyone can examine the changes
made against this git of redwood would be as follows:

1. fork this git of redwood
2. clone your fork to your workstation/system
3. apply and commit your changes to your clone
4. push your clone back to your fork
5. then file a pull request

If I have missed something please chime in. Thank you all for the dialog on
this feature request.

**Comment by stern0m1** [comment]
As you may have noticed pull request was created.
It's hard coded to inject either after <head> or <body>.

In redwood.conf you can place  'injection-place head' for injecting after head or 'injection-place body' - after body
