### ISSUE TITLE
Server buffer size defonition, is it exists?

### ISSUE THREAD

**Issue by elico** [andybalholm/redwood#26]
Hey @andybalholm,
I have been using Squid-Cache and RedWood for quite some time and I would like to know if something like: read_ahead_gap of Squid-Cache exists in RedWood.
I am using it here since I have a server in an unrestricted and unlimited traffic zone in a server farm and a DSL line connected to this server farm.
When I am contacting directly many sites what happens is that I'm stuck because of some connection's limit per client and also by some QOS system for the DSL clients.
But the connection to the server farm which terminates the DSL pppoe connection is not restricted by any mean, I can utilize 100% of this segment.
With Squid-Cache I am using "ead_ahead_gap 16MB" and the server does the heavy lifting for me.
Is something like this exists or can be added into RedWood?

**Comment by andybalholm** [comment]
There is nothing like it in Redwood, because Redwood doesn't deliberately do any caching. If it phrase-scans a page, it loads it all into memory before it sends anything to the client. Other than that, the only caching is what the operating system does on the TCP connections.

Am I understanding right that you want Redwood to download as fast as possible from the origin server, without waiting for the client, and cache that in memory (up to a certain amount of data) and dribble it out to the client as the client is ready?

**Comment by elico** [comment]
@andybalholm you are understanding me right but I will not call it cache but "Buffer" and also it would be a a good idea to restrict it since it can cripple a server.
The defaults of Squid-Cache is 16KB and I have seen servers which used more then that and was crippled or got into a situation which they were abused as a part of amplification DOS attack.
I am interested in buffering from the basic 16KB to a reasonable maximum and it would be smart to put some restriction on this feature to somehow prevent DOS attacks.

**Comment by andybalholm** [comment]
Slow clients already put a heavy RAM load on Redwood. Adding this buffering would make that worse, so it would only be useful on servers with very large amounts of RAM. The default should probably stay at no buffering.

If you decide to try to add this, I would recommend wrapping the body of the http.Response in a type that implements ReadCloser and encapsulates the buffering behavior. This wrapping would be done only if the page is not being phrase-scanned and buffering is enabled.

**Comment by elico** [comment]
@andybalholm OK, Thanks.
I will look into this.
