### ISSUE TITLE
santanderbank login issue

### ISSUE THREAD

**Issue by stern0m1** [andybalholm/redwood#28]
I cant login to santanderbank.com through the redwood proxy. I dont get an error just, after i put in my password it takes be back to home page. I confirmed that I can login without the proxy.

I tried with a min redwood setup.

redwood.conf
http-proxy :6502
acls /etc/redwood/acls.conf
tls-cert /etc/redwood/root.pem
tls-key /etc/redwood/root_key.pem
acls.conf
acl connect method CONNECT
ssl-bump connect

Just reporting the issue.

Thanks

**Comment by andybalholm** [comment]
Try adding the following line to acls.conf:

    disable-proxy-headers

Some HTTPS sites freak out when they see an X-Forwarded-For or Via header.

**Comment by stern0m1** [comment]
Worked!
