### ISSUE TITLE
android app ssl certificate

### ISSUE THREAD

**Issue by stern0m1** [andybalholm/redwood#29]
I am getting this type of error when some android apps try to connect with the proxy.
2017-10-11 00:28:53,192.168.1.90,slack.com,slack.com:443,error in handshake with client: remote error: tls: unknown certificate,cached certificate
Does this mean the app is not trusting my CA? i.e. it has a pinned CA?
Thanks

**Comment by andybalholm** [comment]
Yep. That's especially common on Nougat and Oreo. An app compiled for Nougat or higher has to specifically opt in to trusting user-installed certificates; otherwise it won't trust them.

**Comment by stern0m1** [comment]
Is there a setting, if there is ssl certificate issues pass through without filtering?
