### ISSUE TITLE
iptables rules

### ISSUE THREAD

**Issue by stern0m1** [andybalholm/redwood#30]
whats the iptables rules for a linux router to use the redwood proxy in a separate machine on the local network?
Thanks

**Comment by andybalholm** [comment]
I don't know. I'm not an iptables expert, and I don't have a setup like that to test on.

**Comment by elico** [comment]
@stern0m1 If it's still relevant I can provide you with the right rules.

**Comment by stern0m1** [comment]
Thanks. Not relevant.
