### ISSUE TITLE
Content phrases problem

### ISSUE THREAD

**Issue by test1964** [andybalholm/redwood#32]
Hi,
I try to block pages based on: 
< 18+ > 1000

but  it blocks  all pages that have only 18 (it seem not to handle the plus sign)
How to block page that have '18+' (I tried also to put 18\+, but no effect) ? 

Thanks

**Comment by andybalholm** [comment]
There is currently no way to do that. Phrases ignore capitalization and punctuation.

**Comment by thinkwelltwd** [comment]
Use many, specific phrases with moderate scores rather than a few general phrases with high scores. "18+" at 1000 would generate false positives galore.

Also, stripping out punctuation makes text obfuscation much harder, so it's a feature, not a bug.

**Comment by test1964** [comment]
Thanks
