### ISSUE TITLE
URL based filtering

### ISSUE THREAD

**Issue by sts** [andybalholm/redwood#33]
We are looking for a proxy to filter outbound connections from our servers based upon an url whitelist. We thought about running a combination of iptables and [Redsocks](https://github.com/darkk/redsocks) on our servers, which redirects outbund connections to a proxy for filtering ([as done by Spotify](https://labs.spotify.com/2015/10/09/designing-the-spotify-perimeter/))

This still poses problems as adding something like `github.com` to the whitelist exposes quite a lot of content to those servers. We would like to filter this based upon the requested URL such as `https://github.com/andybalholm/redwood.*`. Especially for bumped TLS traffic, as most of the destinations are encrypted already.

Is this something which is possible with redwood or worth considering as a future feature?

**Comment by andybalholm** [comment]
Yes, this is definitely something Redwood can do. The primary focus is on content filtering, but it does URL filtering too. It has two basic kinds of URL rules: literal URLs and regular expressions. To match the path you described, you could do it either of these ways:

    github.com/andybalholm/redwood # literal URL
    /github\.com/andybalholm/redwood/ # regular expression

There is some difference between the two forms. The first one is anchored on the hostname, and matches on the granularity of path elements. So it will match https://github.com/andybalholm/redwood/issues/33, but not https://github.com/andybalholm/redwood-config or https://bogus-github.com/andybalholm/redwood/issues/33. The regular expression does a character-by-character match, so it will match all of those. Regular expressions are more flexible, but you need to be careful that they aren't too flexible.

**Comment by sts** [comment]
@andybalholm because you did not explicitly state it, this works for TLS traffic as well, as long as connections are intercepted?

Also looking thought the documentation, it looks like redwood cannot log the URL it accessed when using the tls-log. Or are bumped connections handled like http requests?

**Comment by andybalholm** [comment]
Once the TLS connection is "bumped" Redwood treats it just the same as an unencrypted connection. The tls log is a log of the connections that were bumped. So it just shows the hostname and iPad address. To see the full url, look in access.log.

**Comment by sts** [comment]
Thanks! I think bug can be closed.

**Comment by sts** [comment]
Thanks
