### ISSUE TITLE
Blocking categories for specific users

### ISSUE THREAD

**Issue by enxoco** [andybalholm/redwood#36]
I'm a little confused as to how you can block certain categories of sites based on the username.  For example, I would like to create a policy that blocks all image searches by certain users while allowing it for others.  I tried adding changing the action to acl under categories/image-search but how can I apply this to a specific username?

**Comment by andybalholm** [comment]
You don't necessarily need to change the category action to acl. All categories are available for use as acls; changing the action to acl just makes the category act more like a normal ACL.

You need to create an acl for the specific user (or users), like this:

```
acl joe-and-fred user-name joe fred
block image-search joe-and-fred
```

**Comment by enxoco** [comment]
I must be missing something.  What should the category action be?  I am using the default config.  I added those two lines in my acl, substituting my username but I can't seem to get it to work right.  It seems like whatever action I specify in the category.conf file is the action that gets applied no matter what the username is.  `root@reverse-proxy:/etc/redwood# cat /etc/redwood/categories/image-search/category.conf 

description: Image Search
action: allow
root@reverse-proxy:/etc/redwood# cat /etc/redwood/categories/image-search/search.list 
default 500

/google\..*tbm=(isch|vid)/
google.com/imghp

bing.com/images
bing.com/videos

video.search.yahoo.com
images.search.yahoo.com
images.google.com
` 

and the lines in my acl

`acl murph username murphphone
acl murphpc username murphpc
block image-search murph
`

**Comment by andybalholm** [comment]
It needs to be `user-name`, not `username`.

**Comment by enxoco** [comment]
Perfect, I knew their was something simple that I was missing.
