### ISSUE TITLE
blackweb lists compatability

### ISSUE THREAD

**Issue by elico** [andybalholm/redwood#38]
I have seen this blacklist:
https://github.com/maravento/blackweb

And was wondering, what would be the best way to use blackweb lists with RedWood?

**Comment by andybalholm** [comment]
I haven't looked very closely, but you can probably write a simple Perl script to convert the blackweb lists into Redwood's format.

**Comment by elico** [comment]
I will try to write a ruby script since I like it better then perl.
I will dig into it more and try to update about it.
Thanks!
