### ISSUE TITLE
Craigslist.org very slow to load

### ISSUE THREAD

**Issue by enxoco** [andybalholm/redwood#39]
I am noticing that whenever I try to access Craigslist through redwood it is taking a really long time.  Over 2 minutes to fully load a page.  The issues appears to be related to loading the javascript and css assets.

I am attaching a screenshot from developer tools to show what I mean.

![craigslist](https://user-images.githubusercontent.com/34722899/34573308-d06bad9a-f141-11e7-8887-9ff2ed634ce5.png)

What can I do to get around this?

**Comment by enxoco** [comment]
I also get the following errors in my log file:

`2018/01/04 11:16:43 error while reading response body (URL: https://newyork.craigslist.org/): context canceled
2018/01/04 11:16:58 error while reading response body (URL: https://newyork.craigslist.org/): context canceled
2018/01/04 11:18:46 error while reading response body (URL: https://www.craigslist.org/js/general-concat.min.js?v=ec75caad3953678a82856bd9c30fbc7b): context canceled
2018/01/04 11:22:34 error while reading response body (URL: https://www.craigslist.org/js/general-concat.min.js?v=ec75caad3953678a82856bd9c30fbc7b): context canceled
`

**Comment by andybalholm** [comment]
It takes me about three seconds. What are you running Redwood on? What is your network topology?

**Comment by MurphCCC** [comment]
I’m currently running it on a digital ocean droplet.  I haven’t noticed
this with any other sites.  Craigslist seems to be the only one so far.

**Comment by andybalholm** [comment]
How fast does the droplet load those resources with `curl` on the command line? How much RAM does it have, and how much is free?

**Comment by enxoco** [comment]
This is the error I get when running curl:

`user@p1:~# curl https://craigslist.org
curl: (56) GnuTLS recv error (-110): The TLS connection was non-properly terminated.
`

**Comment by enxoco** [comment]
Well it appears that I get that error whether I am going through the proxy or not.

**Comment by andybalholm** [comment]
Is that with running curl on the command line on the droplet?

**Comment by enxoco** [comment]
I get that error running it on the droplet but I also get that error on my computer when im not going through the proxy.

**Comment by enxoco** [comment]
If I run the following on my computer

`curl https://www.craigslist.org/styles/homepage.css`

The response is very quick, however when I ran it on my droplet it was over 1 minute.  I will try running it on another server and report back.

**Comment by andybalholm** [comment]
It sounds like it is a problem in the network between your droplet and CraigsList's server. Maybe they have that IP address tarpitted because a previous user was crawling the site too fast from there.

**Comment by andybalholm** [comment]
It looks like Craigslist throttles DigitalOcean's whole IP address range:

https://www.digitalocean.com/community/questions/curl-works-very-slow-on-craigslist-org

To test this, I ran the command on a droplet that i have, and it's slow there too.

**Comment by enxoco** [comment]
I tried this on one of my Amazon EC2 instances and it works just fine.  Must be something with Digital Ocean or with my ip then.
