### ISSUE TITLE
Captive Portal Redirect

### ISSUE THREAD

**Issue by enxoco** [andybalholm/redwood#40]
I have noticed that when I connect to a network with a captive portal I do not get a splash page allowing me to authenticate and am thus unable to browse the web.  This happens on my iPhone as well as my laptop.  I am aware that this is not necessarily an issue with Redwood but with proxies in general and was wondering if you knew of a solution.

**Comment by andybalholm** [comment]
It's easy to fix on an iPhone (assuming you're setting the proxy with a profile from Configurator or Profile Manager). There is a checkbox for "Allow bypassing proxy to access captive networks." I don't know of a fix for Windows or MacOS.

**Comment by enxoco** [comment]
I was aware of that, however it did not seem to be working.  Looking into it I believe it was just an issue with the WiFi network I was on.  Even without Redwood I was not able to get the splash page to come up on my phone.  I just wasn't sure if their was another way around it.
