### ISSUE TITLE
Serve PAC file over HTTPS instead of HTTP

### ISSUE THREAD

**Issue by enxoco** [andybalholm/redwood#41]
What would it take to have Redwood serve PAC files over HTTPS instead of HTTP?  I believe there are issues with some apps on iOS that won't respect all the rules in PAC file if it isn't served securely.

**Comment by andybalholm** [comment]
You would need to add new configuration parameters to specify the HTTPS port for PAC files and the TLS certificate and key to use, and add a line like this to an appropriate place:

```
go http.ListenAndServeTLS( /* values from your new configuration variables go here */, http.HandlerFunc(handlePACFile))
```

It would probably go in the `main` function in redwood.go. Things would get a little more complicated if you wanted to make it work correctly with reloading the configuration.
