### ISSUE TITLE
[Enhancement] Project Structure

### ISSUE THREAD

**Issue by kudo28** [andybalholm/redwood#44]
I have inspected your project and found that the current structure is somehow confusing and hard to scale.
Do you have any plan in the future to refactor the current code towards the Package Oriented as Go structure?
Moreover, do you plan to supply the way to CRUD config and store  in db?

**Comment by andybalholm** [comment]
Do you have suggestions for things that should be split out into separate packages?

(No, I have no plans to make Redwood depend on a database to store its configuration.)

**Comment by thinkwelltwd** [comment]
>  Moreover, do you plan to supply the way to CRUD config and store in db?

Rather than require a database dependency in Redwood, you could build a CRUD app that generates the Redwood config files.

**Comment by kudo28** [comment]
> Do you have suggestions for things that should be split out into separate packages?
> 
> (No, I have no plans to make Redwood depend on a database to store its configuration.)

I think that the business layer should be put at packages for other packages (and main package) to import? Doing that, this project is easy to scale.
For example, as the proxy use the URL matcher and Phrase Scanner, we can put two of these into two packages. And when come into running, we can supply this package the repository they need as the main function read config from file,...

**Comment by andybalholm** [comment]
Do you mean that we should be able to substitute a different URL matcher and phrase scanner at runtime, by specifying the package name in a config file?

**Comment by kudo28** [comment]
Not really. I mean we should divide into separate packages because maybe in the production, sometimes we want to scan URL only and some other cases. If divided, we only need to call the URL package and ignore the Phrase Scanner package. Do you get my idea? 
The current structure is monolithic and not flexible. I think we should refactor it.

**Comment by thinkwelltwd** [comment]
> I mean we should divide into separate packages because maybe in the production, sometimes we want to scan URL only and some other cases. If divided, we only need to call the URL package and ignore the Phrase Scanner package. Do you get my idea?


If phrase scanning is _never_ required for a given use case, you could just never enter phrases in the category files.

But I assume you have a situation in mind where the URL scanning is sometimes all that's required but sometimes phrase scanning, on the same deployment and process lifecycle. But I can't picture what such a situation might be. Could you give a real-world scenario of where the current structure is problematic?

**Comment by kudo28** [comment]
Sorry for not clarifying the detail. Maybe we need to discuss more about this.
In my opinion, if we keep the structure like this, when we want to add features, all we can do is adding code to main package, then this will create a lot dependencies. My idea is to make the redwood as an independent package. 
When we want to run, we only need to call code from the package in the main package, which reduces dependencies. When we want to integrate to other systems, it will be much easier. When we want to integrate other package, it will,too. 
So, have I made it clear?

**Comment by thinkwelltwd** [comment]
"we" (as defined by the primary users of redwood in production) haven't needed to split / refactor / reorganize the code to integrate it into a larger system.

So when someone comes along with hypothetical requirements, and asking for work to be done on their behalf, then specific details and real scenarios should be presented.

So no, it's still not clear. What other systems should it be easier to integrate into, and what dependencies are currently a burden to include (phraselist scanning doesn't need to be one of these, as an alternative was pointed out earlier).

Meanwhile you also requested that Redwood query a database for config files, which would mean _adding_ a dependency. :wink:

To say it another way, open source projects revolve around scratching itches. What itches are you having that you need scratched?
