### ISSUE TITLE
Regex support for negative lookbehind/lookahead

### ISSUE THREAD

**Issue by cbuijs** [andybalholm/redwood#45]
Hi,

Seems that the regex implementation doesn't support negative lookbehind/lookahead syntax/feature.

See here for more info:
[Regex Tutorial - Lookahead and Lookbehind Zero-Length Assertions](https://www.regular-expressions.info/lookaround.html)

Below an example of how I would like to use it (the `?!` part is the negative lookahead):

- `^(.*\.)*((?!font[s]*).)*\.googleapis\.com$`
- Meaning whitelist `googleapis.com` domain, except if it is `fonts.googleapis.com`

This would make it easier just to block just one subdomain instead of whitelisting a lot if not all possible subdomains.

It is not a deal-breaker but makes it easier to whitelist stuff from a regex perspective.

See some regex examples here I use:
https://github.com/cbuijs/accomplist/blob/master/chris/regex.white
https://github.com/cbuijs/accomplist/blob/master/chris/tld-black.regex

The second one is interesting as it blocks anything except valid TLD's registered by IANA (it is a blacklist as it negates).

Cheers,
-Chris

**Comment by thinkwelltwd** [comment]
> Seems that the regex implementation doesn't support negative lookbehind/lookahead syntax/feature.

Redwood uses Go's re2 engine which has that behavior.

However, you can accomplish what you want as the scoring is cumulative, so can add rules like so:

```
googleapis.com 200
fonts.googleapis.com -200
```
The 2 domain matches will be more efficient than 1 regex anyway; Go's regex engine isn't the fastest one in existence.

**Comment by cbuijs** [comment]
BTW, it should be the following to work correctly:

```
googleapis.com -200
fonts.googleapis.com 200
```

**Comment by andybalholm** [comment]
It all depends on whether it's in a blocked or allowed category…
