### ISSUE TITLE
Tagging versions

### ISSUE THREAD

**Issue by elico** [andybalholm/redwood#47]
Currently there aren't any official versions tagging for the software.
If there is a possibility to say that this revision is has some versioning it would nice.
@andybalholm  I can say that if you have a list of things that the software does then it's a list and can be percented from to V1.0 from 0% to 100% in some fashion.

What do you think?

**Comment by andybalholm** [comment]
@thinkwelltwd has been assigning version numbers for his RPM packages of Redwood. I suppose those would be a good starting point for any versioning scheme.

**Comment by elico** [comment]
@andybalholm Where can I find this RPM package from @thinkwelltwd ?

**Comment by andybalholm** [comment]
They are just for our internal use. But I was thinking his versioning scheme would be the place to start.

**Comment by andybalholm** [comment]
There isn't a complete record of the version numbers that @thinkwelltwd has assigned, but I've tagged the versions from the last couple of years now.
