### ISSUE TITLE
Error in the README example of blockpage value

### ISSUE THREAD

**Issue by elico** [andybalholm/redwood#50]
For quite a while I didn't found what is causing my setup to generate bad block page.
ie empty pages..
In the README the example is:
`blockpage "/etc/redwood/block.html"`

but it only works like this:
`blockpage /etc/redwood/block.html`

Without the double quotes.

**Comment by andybalholm** [comment]
After 8 years, somebody noticed the bug! It’s fixed on the master branch now.

Andy

**Comment by elico** [comment]
Actually I noticed since day 0 but.. only now back to testing.

> 
> After 8 years, somebody noticed the bug! It’s fixed on the master branch now. Andy
> […](#)
