### ISSUE TITLE
SARG support

### ISSUE THREAD

**Issue by mrbluecoat** [andybalholm/redwood#53]
Can Redwood's log file be formatted for SARG support: https://sourceforge.net/p/sarg/wiki/Logs%20options/

**Comment by andybalholm** [comment]
There are programs that depend on the existing format. But if someone wants to add a configuration option (`dansguardian-log-format` or `squid-log-format`), I would accept a pull request.

**Comment by mrbluecoat** [comment]
I'm not especially committed to SARG, it's just actively maintained. Do you have a recommendation for an alternate log analyzer and reporting solution?

**Comment by andybalholm** [comment]
Not really; we use a custom program developed in house.

**Comment by HiranChaudhuri** [comment]
How about using [Matomo](https://matomo.org) for log analysis? It is open source, supports many formats and is open for new formats - so in case it is even documented how redwood might be imported there.

**Comment by andybalholm** [comment]
People are free to analyze the logs however they want.
