### ISSUE TITLE
pruning elements

### ISSUE THREAD

**Issue by mrbluecoat** [andybalholm/redwood#57]
Quick question, my `/etc/redwood/pruning.conf` file has this line but the "More information..." link still shows up when I browse to http://example.com/

```
example.com a
```

Thoughts?

**Comment by andybalholm** [comment]
Do you have an ACL with a `phrase-scan` action that applies? Pruning only happens when the content is being scanned.

**Comment by mrbluecoat** [comment]
Ah, missed that. Thanks!
