### ISSUE TITLE
Troubleshooting ssl-bump

### ISSUE THREAD

**Issue by HiranChaudhuri** [andybalholm/redwood#60]
While still new to redwood, I am trying to ssl-bump some connections. However regardless which URL I try to connect to, I keep getting handshake errors like

```
2021-02-27 21:48:16.563560,192.168.178.68,www.google.com,www.google.com:443,error in handshake with client: EOF,cached certificate,aa7744226c695c0b2e440419848cf700
2021-02-27 21:48:16.675060,192.168.178.68,www.google.com,www.google.com:443,error in handshake with client: remote error: tls: unknown certificate,cached certificate,aa7744226c695c0b2e440419848cf700
```

A `curl`command from the machine running redwood to the same URL seems to reveal the expected result. When trying `redwood -test :url:`I get up to `downloading content` and some HTTP status code.

What may be going wrong? What else may I test to drill down?

**Comment by andybalholm** [comment]
Have you installed the root certificate that Redwood is using for SSLBump as a trusted root on the client computers?

**Comment by HiranChaudhuri** [comment]
I did install a 'good enough' root certificate. It is a intermediate CA certificate signed by my root CA - however the client has not yet imported it. Let me do that and see if the error goes away...

**Comment by HiranChaudhuri** [comment]
So my root CA's certificate is imported. But I realize there is no setting for intermediate certificates or a certificate chain in redwood. Would that imply I better install the certificate configured in redwood also in my clients?

**Comment by andybalholm** [comment]
The only configuration I've ever used has been to install (on the client) the exact same certificate that Redwood uses.

**Comment by HiranChaudhuri** [comment]
Indeed there is an issue with my certificate. Firefox rejects it as it is not a proper CA certificate.

**Comment by andybalholm** [comment]
It's probably OK if it has that Extended Usage attribute, but it probably needs to have the "Certificate signing" one too.

**Comment by HiranChaudhuri** [comment]
You are right here.

I drilled it down to my root CA having issued a certificate I intended to use as intermediate but it is not allowed for CA use. This needs to be fixed on the CA.

Thank you for pointing me to the certificate installed on redwood - it saved me a lot of time.
