### ISSUE TITLE
Troubleshoot/verify content pruning

### ISSUE THREAD

**Issue by HiranChaudhuri** [andybalholm/redwood#62]
After I got most of my redwood requirements I am now trying to use the pruning capabilities to remove the youtube video list that usually occurs on the right to every video that is playing. Somehow I simply do not get it right, and eventually I am not even sure
- whether any pruning occurs at all
- whether I use the correct url or regex
- whether the CSS selector is the problem

A lot of possible mistakes and I have no feedback what is happening. What may I look at to verify the listed items one by one?

**Comment by andybalholm** [comment]
For points 1 and 2, look at the line in access.log. It will contain the word "pruned" if any pruning happened on the page.

For point 3, try the CSS selector in your browser's developer tools.

One thing to keep in mind is that the pruning only affects the HTML of the page itself, not what is added by JavaScript. Sites like YouTube are pretty AJAX-heavy, so pruning them can be difficult.

**Comment by HiranChaudhuri** [comment]
I will look closer for the access logs then. Is there any hint available which of the rules actually got applied? Something similar to listing all the categories that match for a request.

AJAX can be indeed a problem. Is there some pattern available? How might others have done something similar?

**Comment by andybalholm** [comment]
No, the only logging for pruning is whether it happened or not.

If the content is being filled in by AJAX, you need to find the request that actually loads the data you don't want, and block that request.

**Comment by HiranChaudhuri** [comment]
Indeed, I can see the keyword 'pruned' on the URLs I was targeting at.
Is there any chance to check the content? Before and/or after pruning?

**Comment by HiranChaudhuri** [comment]
Ok, it seems there is no further logging and no other information available for pruning.
I wll try then what I can do.

So far the best solution for me is based on the client. Extensions like Adblock Plus or UBlock Origin allow to prune websites' content regardless of how they were loaded. Much easier to configure, but easily to be circumvented as they are on the client.
