### ISSUE TITLE
Block pages missing CORS or another header

### ISSUE THREAD

**Issue by elico** [andybalholm/redwood#67]
I have being to debug today a block which was done on a specific subdomain of rutube.ru.
One of the static subdomains was marked for nudity by one of my upstream categorizing services.
I have seen a 403 response but it was blocked from the browser because the 403 response was missing the right CORS headers.
I verified that the original web service has the next CORS Headers:
`Access-Control-Allow-Origin: *`

Which when thinking about it, should be present in all block pages responses to allow the browser receive the page through the JS.
To identify that the 403 was from redwood I had to login the server and see the logs compared to see a simple response header or response.

I believe that the right solution is to add to all block pages the right CORS Headers and if the decision is to not add or even if to add there headers, I believe a specific header should be embedded in the response so it would be easy to identify that the response is from RedWood.

@andybalholm I can write the code (a single line..) what do you think about it?

**Comment by andybalholm** [comment]
Did the lack of the header keep the request from even showing up in the browser developer tools?

**Comment by elico** [comment]
@andybalholm It appears of-course it appears.
However it shows a 403 response with a CORS issue.
The page looks distorted and doesn't show any sign of a block.
When I tried to understand where the CORS issue is from I had to manually get to cli and see that the origin server is an nginx one.
When I saw that the origin service has CORS allowed for all domains and it's nginx I understood that the page was probably blocked by RedWood and verified with the logs (lots of urls.... was very hard to find them in production).
The issue is that when CORS is not allowed by the headers the browser discards of the response body.
If I had the response ... it would have taken my a second to recognize.

It was much easier for my if I had an addition header in the response let say like "X-Redwood-Block: Blocked" or the CORS enabled on all block pages.

**Comment by andybalholm** [comment]
@thinkwelltwd What do you think? I can't think of any reason not to add the CORS header, but maybe I'm missing something…

**Comment by thinkwelltwd** [comment]
> I can't think of any reason not to add the CORS header

I can't either; SGTM.

**Comment by andybalholm** [comment]
@elico Go ahead.

**Comment by elico** [comment]
@andybalholm It's this simplest patch(I think).
I think a pull request is too much for this to me right now.

```
diff --git a/blockpage.go b/blockpage.go
index 82963d2..61babb0 100644
--- a/blockpage.go
+++ b/blockpage.go
@@ -83,6 +83,9 @@ func (c *config) aclDescriptions(rule ACLActionRule) []string {

 // showBlockPage shows a block page for a page that was blocked by an ACL.
 func showBlockPage(w http.ResponseWriter, r *http.Request, resp *http.Response, user string, tally map[rule]int, scores map[string]int, rule ACLActionRule) {
+       w.Header().Set("Access-Control-Allow-Origin", "*")
+       w.Header().Set("X-Redwood-Block-Page", "403 Access Denied")
+
        c := getConfig()
        switch {
        case c.BlockTemplate != nil:
```
