### ISSUE TITLE
Improvement: Unblock requests function

### ISSUE THREAD

**Issue by HiranChaudhuri** [andybalholm/redwood#71]
So I am using redqood in a SOHO setup, and it works quite well.
Now and then I have to look at the categorzation and tweak a bit. So far so good.

For users it is quite frustrating to see the block page too often. But despite the message to talk to their admin they rarely do.
For me it is annoying to first recreate the scenario (what URL is blocked? How did you access it?), especially since some URLs are only allowed with the correct referrer.

So I thought about extending the block page with a link to send an unblock request. The user could give his name and a justification, the other data (URL and Referrer or alternatively timestamp to refer to the proxy log) could be added automatically and then the data is sent to some service that keeps track of it.

Would it be feasible if Redwood offered such a service as part of it's API? Or should this be something independent on purpose?

**Comment by andybalholm** [comment]
It should probably be a separate service. You can easily make the blockpage have a form that posts to that service.

**Comment by HiranChaudhuri** [comment]
Ok, then I was not completely off that track. Thank you.
