### ISSUE TITLE
Do categories support hot reload?

### ISSUE THREAD

**Issue by mrbluecoat** [andybalholm/redwood#72]
Does Redwood support hot reload of categories? For example, if I edit /categories/test/mytest.list with a new entry do I need to reload /usr/local/bin/redwood or does redwood pick up the change automatically? In my testing it appears I need to restart Redwood.

**Comment by andybalholm** [comment]
It can do a hot reload, but it doesn't do it automatically. You need to send it SIGHUP to trigger a reload.

**Comment by mrbluecoat** [comment]
`service redwood reload` from #73 fixed this for me
