### ISSUE TITLE
Redwood systemd service provided?

### ISSUE THREAD

**Issue by mrbluecoat** [andybalholm/redwood#73]
Does Redwood come with a systemd service? #22 references one but I can't find it in the code and my installation doesn't detect one. I also checked https://github.com/andybalholm/redwood-config  I'm currently using https://github.com/bmc/daemonize as a workaround.

**Comment by mrbluecoat** [comment]
My executable was in `/usr/local/bin` and also the `/var/run` path has been deprecated in favor of `/run` so this version is working better for me:

```
cat > /etc/systemd/system/redwood.service <<EOF
[Unit]
Description=Redwood Content Filter
After=network.target

[Service]
Type=simple
ExecStart=redwood -pidfile /run/redwood.pid 2>>/var/log/redwood/errors.log
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-abort
StandardOutput=null
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF
```
However, the reload still doesn't seem to be hot loading updates to categories (#72), only a `service redwood restart`. Does your code handle the `HUP` signal? (e.g. https://gist.github.com/andelf/5889946 )

**Comment by andybalholm** [comment]
You're sending SIGHUP to $MAINPID, but you're not assigning to that variable anywhere. So the signal isn't getting to Redwood.

**Comment by andybalholm** [comment]
What, if anything, shows up in /var/log/redwood/errors.log when you send SIGHUP?

**Comment by mrbluecoat** [comment]
Dumb error on my part -- forgot to escape the dollar sign on `$MAINPID` when writing out the file programatically. I also had `/var/run` instead of `/run` in my follow-up test with your code which also didn't point to the pid file. I've updated both my posts above and confirmed it's working with `service redwood reload`

**Comment by mrbluecoat** [comment]
Here's the official contents of the **redwood.service** file that worked for me:

```
[Unit]
Description=Redwood Content Filter
After=network.target

[Service]
Type=simple
ExecStart=redwood -pidfile /run/redwood.pid 2>>/var/log/redwood/errors.log
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-abort
StandardOutput=null
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
```

**Comment by mrbluecoat** [comment]
and here's how to activate it:

```
systemctl enable redwood
systemctl start redwood
```
