### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by mrbluecoat** [andybalholm/redwood#74]
@andybalholm this is a seriously awesome project that deserves a lot more attention. Any thoughts about adding a logo to get more awareness? Here's a quick concept I threw together - feel free to use or ignore:

![redwood](https://user-images.githubusercontent.com/382164/117872669-d0cc1f00-b253-11eb-9b90-09fa833c89d8.png)

SVG: https://drive.google.com/file/d/1LnEwrtkW3gI9I-vsn9owKnHHVv3NseWw/view?usp=sharing

Sources:
- https://www.logologo.com/logo.php?id=41
- https://fonts.google.com/specimen/Passion+One?query=passion

**Comment by andybalholm** [comment]
We've never paid much attention to branding for Redwood itself, since it's a behind-the-scenes component of our product. But it wouldn't hurt to have a logo.

That particular tree looks more like an oak than a redwood, though.

We would need to make sure any logo we would add would have a compatible license.

**Comment by mrbluecoat** [comment]
Here's another idea using public domain assets in case you find it helpful. That said, logos are personal taste so now that I've planted the seed (no pun intended), I'll leave the artistic direction in your hands.

![redwood2](https://user-images.githubusercontent.com/382164/117904636-9465e680-b286-11eb-8600-5f54a8beef3e.png)

SVG: https://drive.google.com/file/d/1PZU_GprKtm3PuO0FlcvDXrElhn5Pyfah/view?usp=sharing

Sources:
- https://publicdomainvectors.org/en/free-clipart/Conifer-cone/59836.html
- https://www.fontspace.com/bsd-font-f21260
