### ISSUE TITLE
auto HTTP to HTTPS redirect when only port 443 is avaliable

### ISSUE THREAD

**Issue by elico** [andybalholm/redwood#76]
I was thinking about a nice feature which might help in many use cases.
There are sites and servers which doesn't answer to http and port 80 for https everywhere support.
In these specific cases I believe that a 301/307 redirection to the HTTPS version might be useful.
Since redwood is intercepting the connection anyway it just needs to verify that port 443 is reachable(or not...) and then redirect towards the HTTPS(443) version of the site and domain.

What do you think about this idea?

**Comment by andybalholm** [comment]
I would think that offering an automatic redirect on port 80 is the site's responsibility, not the proxy's.

**Comment by elico** [comment]
@andybalholm I am not talking about the responsibility.
Web browsers try both port 443 and 80 then they will use what is available.
The issue with redwood is that it's receiving the request on port 80 which will make the browser think that there is a service there.
You can see sometimes the timeout error response from RedWood when it was actually a reject or drop or another issue.
I assume that since Redwood is causing the browser to not retry on port 443 RedWood as a proxy should help with this.
It's an enhancement request which is related to a bug which RedWood is causing.
The best solution would be for RedWood to check the remote server when the syn is being received from the client but...
Well I do not see you or anyone enhance else enhance RedWood to this level.

**Comment by thinkwelltwd** [comment]
>  It's an enhancement request which is related to a bug which RedWood is causing.

@elico could you flesh out more what you're describing? I would've agreed with @andybalholm that this sounds like a reverse proxy problem, but you're saying Redwood has a bug.

>  There are sites and servers which doesn't answer to http and port 80 for https everywhere support. ... Web browsers try both port 443 and 80 then they will use what is available.

Am I understanding you to say that a given domain, when unproxied browsers encounter http://www.https-everywhere-domain-without-reverse-proxy.com that they auto-redirect to https://www.https-everywhere-domain-without-reverse-proxy.com, and that when Redwood is involved this browser-based auto-redirect fails?

Am I correctly understanding your use-case scenario? If so, do you have a real-world domain where this behaviour can be experienced?

**Comment by hiranchaudhuri1** [comment]
I absolutely agree to offering a redirect http->https is the site's responsibility.
However today, when users enter a domain name into their browser the browser will first try to prepend https:// and only if that does not work will try http://. This is Google's initiative to make the web more secure.
The impact is that more and more sites might stop configuring a redirect at all although we believe it is their responsibility.

Now if we look at the behaviour of browsers behind a proxy, it would be nice if the user experience could be as similar as without a proxy configured.

Yet it seems (I have not checked this) that this automatic check for https:// urls is not performed. Hence elico created this suggestion, and I see a point here. It may be worth acting despite I still believe in the above statement.

**Comment by elico** [comment]
An example is:
http://inputapi.theneura.com/

**Comment by andybalholm** [comment]
There would be no way to distinguish between intermittent network issues and a misconfigured server. So if we do this, it should be 307 (Temporary Redirect), not 301(Moved Permanently).

**Comment by elico** [comment]
@andybalholm Understood.
I did knew about the 307 and still it was worth mentioning this subject.
