### ISSUE TITLE
Will it be possible to integrate Tproxy interception?

### ISSUE THREAD

**Issue by elico** [andybalholm/redwood#8]
I wrote a tiny example for Linux tproxy usage at: https://github.com/elico/go-linux-tproxy
And was wondering if we can somehow add tproxy support for redwood?

**Comment by andybalholm** [comment]
It looks like it would be a real challenge. If I understand correctly, the point of TPROXY is to make the requests to the server look like they are coming from the client instead of from the proxy. Redwood currently shares a pool of server connections between all the clients; you would need to bypass that and have a custom TPROXY-capable RoundTripper for each client connection.

**Comment by elico** [comment]
@andybalholm I wasn't aiming for the full blown pack but merely the option to use a TPROXY listening socket\listener.
I am also pretty sure that a RoundTripper for each connection is too much.
Technically I was thinking in the past about a RoundTripper like pool per src IP.
It's pretty simple to define a Connection function that the RoundTripper or other components can use instead of the existing one.

**Comment by andybalholm** [comment]
What is the advantage of using a TPROXY listening socket over iptables REDIRECT rules? (If you're not going the full TPROXY route.)

**Comment by elico** [comment]
@andybalholm this is the first step that will open new doors.

**Comment by andybalholm** [comment]
I don't have a need for it myself, but I'm open to pull requests, and available to give advice.

**Comment by elico** [comment]
@andybalholm great.
It will take more the a second since I am still learning the code for quite some time.

**Comment by elico** [comment]
Not promising anything soon but I compiled an example of how it would be possible to create a http client with a customized source ip:
https://github.com/elico/go-linux-tproxy/blob/master/examples/tproxy-http-client.go
I will need to polish and clean the tproxy code but the above code was tested to contact google with the fake IP.

**Comment by andybalholm** [comment]
Is TPROXY the only way to do interception of IPv6 on Linux?

**Comment by elico** [comment]
@andybalholm as far as I know you can use REDIRECT for both IPv4 and IPv6 but it then turns the gateway from a simple router to a NATting router.
It is fine for home and small offices but for ISP's they must have a way to Intercept "transparently" many connections if they want to filter MASSes.
If your goal is small offices and small homes then you don't need to support TPROXY.
Let me know if we are setting the bar of the software higher then small offices and tiny ISP's.

**Comment by andybalholm** [comment]
The itch Redwood was created to scratch is small offices. Only one of our clients has a network that is too large for a /24 subnet to be adequate.

However, the project has generated some interest from potential users that are much larger, including a national government. It wouldn't be practical to NAT a whole country, or even a regional ISP.

**Comment by elico** [comment]
@andybalholm Can we move from public comments to skype or something else in the coming week?
I know and believe that many would like to put some money for your work.
What I can offer is guidance and a testing setup compared to Squid-Cache which I am a part of it's development team.

**Comment by elico** [comment]
@andybalholm do you need me to do some codiing?
Do you prefer public over private?

**Comment by andybalholm** [comment]
@elico, I tried to contact you on Skype this morning, but maybe I guessed the wrong username. I'm andybalholm there.

**Comment by elico** [comment]
@andybalholm added you.
Let me know when i

**Comment by elico** [comment]
Sent you and email cause I couldn't reach you on skype.
