### ISSUE TITLE
Documentation: is using another classification service still supported?

### ISSUE THREAD

**Issue by HiranChaudhuri** [andybalholm/redwood#80]
It has been some time that I started using Redwood - it is nice and compact and works without requiring much attention.

Now I am thinking to customize the rules when a site is allowed or not. Somehow I remember that Redwood could be configured to use some other service to take such a decision. But when going through the readme, especially https://github.com/andybalholm/redwood#classification-service I cannot see such a feature any more.

Is this no longer supported? Or is just documentation about this feature missing?

**Comment by HiranChaudhuri** [comment]
Maybe I remember correctly as I found https://github.com/andybalholm/redwood/blob/master/config.go#L205 but do not really know how to use it.

**Comment by andybalholm** [comment]
It's never been documented. 

It's not really necessary now that there is support for Starlark scripting. A script can access external services too, and it's more flexible. (And there's a good chance you can just write your extra logic in Starlark, and skip the external service.)

But what kind of customization are you wanting to do? Maybe there's an even easier way to do it.

**Comment by HiranChaudhuri** [comment]
Since you are asking...

I use Redwood to filter traffic for my kids. They are not supposed to access every site, but filter by content is so much smarter than domain names. But behaviour changes over time, and they start using the computer whenever. I'd like to limit internet access by time, or allow them to extend the given times by earning vouchers. While I do not expect Redwood to come with such a system out of the box I thought to implement a webapp myself and let Redwood attach to it.

Thinking about Starlark (are we talking about this? https://github.com/bazelbuild/starlark) I could probably place part of the logic there, but the webapp to manage the vouchers would still be needed. Does such a system already exist?

**Comment by andybalholm** [comment]
Yes, that's the page on the Starlark language. Redwood's support for scripting with Starlark is documented at https://github.com/andybalholm/redwood/blob/master/starlark.md

Starlark is basically a subset of Python. The Starlark implementation in Redwood is not as limited as the Starlark in Bazel. But it's still missing a lot of things that are in regular Python.

**Comment by HiranChaudhuri** [comment]
Another idea could be to use [JSON web tokens](https://en.wikipedia.org/wiki/JSON_Web_Token). This could speed up processing. Can Starlark be used to validate such tokens, and redirect the traffic in case it is invalid?

**Comment by andybalholm** [comment]
Likely. It's Turing-complete. (Unlike Bazel's version of Starlark.)

But I wouldn't recommend doing a lot of cryptography in pure Starlark. It's pretty slow. You'd be better off checking the user's status against an external server than trying to verify cryptographically-signed tokens.

**Comment by HiranChaudhuri** [comment]
Ok, thanks for the heads up.

So what are the possibilities for this solution? Given that there is a URL I could trigger in Starlark that asks for permission accessing some URL, how could a response look like? Should it be simply JSON? What information can be passed via Starlark to my service? Would it be all the classification, keywords, cookies?

Maybe you could provide a small example of Redwood configuration, and I will try to take it from there?

**Comment by thinkwelltwd** [comment]
> Maybe you could provide a small example of Redwood configuration, and I will try to take it from there?

I make extensive use of Starlark scripts. Here's one to classify images by hashing. In acls.conf:

`starlark-script /path/to/image_classify_response.star`

```python
load("/path/to/module/image_precheck.star", "skip_image_analysis")

def filter_response(response):
    """
    On image responses, check to see if the image was flagged
    as inappropriate.
    """
    if skip_image_analysis(response):
        return

    image = response.thumbnail(128)
    if not image:
        return

    json_body = {
        'image': base64.encode(image),
        'url': response.request.url,
    }
    resp = http.post('http://127.0.0.1:10009/image/flagged/', json_body=json_body)

    if resp.status_code > 299:
        print('Image classification failed %s' % response.request.url)
        return

    category = resp.json().get('category')
    if category:
        response.scores[category] = 500
        print('Image hash matched! Added category "%s" to %s' % (category, response.request.url))
```

**Comment by HiranChaudhuri** [comment]
So the script does not return anything back to the caller, instead it just modifies the passed objects (session, request, response).

What happens to print statements writing to stdout/stderr? What happens if the function throws an Exception?
What happens if I register several scripts for one of the three events (ssl_bump, filter_request, filter_response)?

**Comment by thinkwelltwd** [comment]
> So the script does not return anything back to the caller, instead it just modifies the passed objects (session, request, response).

Redwood's the caller, so if the response is used by the caller, that means you've modified Redwood to make it do something with the result. Which I suppose is technically possible, but that'd be a great tedium. So mutating the `request`, `response`, or `session` objects is the whole point of "extending Redwood without touching Redwood".

> What happens to print statements writing to stdout/stderr? What happens if the function throws an Exception?

[The output from Starlark functions (print statements and error tracebacks) goes to a CSV log file specified with the starlark-log configuration option.](https://github.com/andybalholm/redwood/blob/master/starlark.md#language-and-library-notes)

> What happens if I register several scripts for one of the three events (ssl_bump, filter_request, filter_response)?

[Register as many as you want, each in its own file. (be sure to link the file with `starlark-script /path/another/file.star`](https://github.com/andybalholm/redwood/blob/master/starlark.md#starlark-scripting)

**Comment by HiranChaudhuri** [comment]
Thank you for the explanation. I think I understand now.
So I will try to create my web application and connect Redwood to my application via Starlark. :-)

**Comment by mrbluecoat** [comment]
> > Maybe you could provide a small example of Redwood configuration, and I will try to take it from there?
> 
> I make extensive use of Starlark scripts. Here's one to classify images by hashing. In acls.conf:
> 
> `starlark-script /path/to/image_classify_response.star`
> 
> ```python
> load("/path/to/module/image_precheck.star", "skip_image_analysis")
> 
> def filter_response(response):
>     """
>     On image responses, check to see if the image was flagged
>     as inappropriate.
>     """
>     if skip_image_analysis(response):
>         return
> 
>     image = response.thumbnail(128)
>     if not image:
>         return
> 
>     json_body = {
>         'image': base64.encode(image),
>         'url': response.request.url,
>     }
>     resp = http.post('http://127.0.0.1:10009/image/flagged/', json_body=json_body)
> 
>     if resp.status_code > 299:
>         print('Image classification failed %s' % response.request.url)
>         return
> 
>     category = resp.json().get('category')
>     if category:
>         response.scores[category] = 500
>         print('Image hash matched! Added category "%s" to %s' % (category, response.request.url))
> ```

Could this be used with an Image AI classifier to selectively block Google Image results (similar to how Canopy works)?

**Comment by thinkwelltwd** [comment]
> Could this be used with an Image AI classifier...?

Yes, you can access image bytes via the `thumbnail` method on the response. From [the docs](https://github.com/andybalholm/redwood/blob/master/starlark.md#filter_response):

> thumbnail(500): returns a JPEG thumbnail of the response, no more than 500 pixels in width and height. If no thumbnail is available (either because the response body is not a supported image format, or because the body is too large), thumbnail returns None. The default size is 1000 pixels.

You can then base64 encode the image bytes to post to whatever end point you choose.
