### ISSUE TITLE
Use a parent proxy

### ISSUE THREAD

**Issue by dtouzeau** [andybalholm/redwood#82]
Is it possible to use a proxy parent in order to chain redwood and upstream proxy ?

**Comment by andybalholm** [comment]
It used to be (by setting the HTTP_PROXY environment variable). It's been years since we used that feature, though. I think it only works for plain HTTP at this point, not for HTTPS.

**Comment by dtouzeau** [comment]
Not possible to enforce the settings without using environment ?

**Comment by andybalholm** [comment]
Setting environment variables (on the server running Redwood) is the only way to make Redwood use an upstream proxy. And even that is basically unsupported—just a leftover from the time when we were running Redwood with Squid.

**Comment by dtouzeau** [comment]
Thanks...
