### ISSUE TITLE
Update Categories from eGuardian

### ISSUE THREAD

**Issue by UnveilTech** [andybalholm/redwood#83]
Hello,
correct me if I'm wrong, it seems Redwood is based on DansGuardian, right ?
if yes, do you think you could update Categories with the fork e2guardian (https://github.com/e2guardian/e2guardian) ?
it seems Redwood is using old phraselists (https://github.com/e2guardian/e2guardian/tree/v5.4/configs/lists/oldphraselists), eGuardian is now using new phraselists (https://github.com/e2guardian/e2guardian/tree/v5.4/configs/lists/phraselists).

thanks in advance.
bye Fred

**Comment by andybalholm** [comment]
Redwood was designed to replace DansGuardian. But the configuration is not compatible. The configuration in github.com/andybalholm/redwood-config was converted from the DansGuardian phraselists in a semi-automated process using the dg-convert program in this repository. It is not a particularly good configuration, and has seen very little testing in production. 

It would be great if someone would make a better configuration available under an open-source license. Maybe the new E2Guardian phraselists would be a good place to start.

**Comment by UnveilTech** [comment]
Hi Andy,

**Comment by UnveilTech** [comment]
github removed parts of examples...

do you support that format: <adult material>,<extreme nature><70>

**Comment by UnveilTech** [comment]
adult material,extreme nature 70
think keys, value with <>

**Comment by UnveilTech** [comment]
< adult material >,< extreme nature >< 70 >

**Comment by UnveilTech** [comment]
or do you only support that: < adult material > 70

**Comment by UnveilTech** [comment]
[pornography.list.txt](https://github.com/andybalholm/redwood/files/10459980/pornography.list.txt)
that's my e2guardian to redwood, is that ok with you ?

**Comment by andybalholm** [comment]
Redwood doesn't support joining two phrases with a comma like that.

**Comment by andybalholm** [comment]
It looks like it might work. 
But don't ask me; test it and see how it works.

**Comment by UnveilTech** [comment]
Hi Andy,
it works fine, the score is higher and more precise...
use my file as you wish, gift !

bye Fred
