### ISSUE TITLE
How to use ClamAV

### ISSUE THREAD

**Issue by UnveilTech** [andybalholm/redwood#84]
Hi Andy,
there is the key "clamd-socket" available in the config, can you share some details how to use it ?
we set "clamd-socket /var/run/clamav/clamd.ctl" in the conf file but we cannot see any details in the log file...
thanks in advance.

bye Fred

**Comment by UnveilTech** [comment]
manual launch of Redwood:
/usr/local/bin/redwood -c /etc/redwood/redwood.conf
2023/01/23 20:59:08 Redwood v1.8.0

nothing else.
Fred

**Comment by UnveilTech** [comment]
my redwood.conf:
categories=/etc/redwood/categories
threshold 5000
http-proxy 127.0.0.1:6502
clamd-socket /var/run/clamav/clamd.ctl
access-log /var/log/redwood/access.log
acls /etc/redwood/acls.conf

maybe something missing ?

**Comment by thinkwelltwd** [comment]
> maybe something missing ?

I don't know what the contents of your acls.conf file is. Do you have any ACLs specifying which requests should be scanned?

```
acl installers content-type application/dos-exe
acl installers content-type application/exe
acl installers content-type application/msdos-windows
acl installers content-type application/x-exe
acl installers content-type application/x-msdos-program
acl installers content-type application/x-msdownload
acl installers content-type application/x-winexe

virus-scan installers
```

**Comment by andybalholm** [comment]
Also, you're not very likely to get anything interesting to scan till you enable SSLBump (to scan HTTPS connections).

**Comment by UnveilTech** [comment]
ok, thank you for your help guys, appreciated.
