### ISSUE TITLE
EOF as the body of a response

### ISSUE THREAD

**Issue by elico** [andybalholm/redwood#9]
I noticed that sometimes a request is being responded with the text "EOF".
In the logs I found something like:
2016/08/26 03:01:25 error fetching http://www.vassalengine.org/: EOF

Is it a known issue?

**Comment by andybalholm** [comment]
That is what happens when the OS returns EOF on a read or write to the TCP socket underlying the HTTP connection to the server. Usually it means that the http package's connection pool returned a connection that the server has dropped (i.e. the Keep-Alive wasn't really kept alive). 

When RoundTrip returns an error, Redwood returns an HTTP status of 503, with the error message in the body of the response. Perhaps we could make the message more informative, but I'm not sure what else we could do about it.

**Comment by elico** [comment]
@andybalholm Hmm well I do understand the situation but I am not sure that it is it.
I wrote a tiny http proxy myself and I have never seen such a behavior with my software.
If indeed this is the situation then a "retry" should be the action.
I believe that the issue arises at:
https://github.com/andybalholm/redwood/blob/a08973b9fa910b3a4721e4c8295e3d61b61e4f4d/proxy.go#L257
And I can try to add a debug and a fix test.
When I will finish my tests I will let you know.
Am I the first to think about the issue?

**Comment by andybalholm** [comment]
As you obviously figured out (because of your pull request), you aren't the first one to think about the issue. At one point I had two different systems for closing idle connections, at different intervals!

**Comment by elico** [comment]
@andybalholm I have a better suggestion which is to retry when a EOF error happens.
This is also based on the concept that a EOF should never be received from a RoundTripper.
The goal is to either get a connection refused or some other error but EOF should always be retried at least twice.
I will try to find the comment of Brad but no promises, if google will find it for me I will put it here(should be in one of github golang issues).

**Comment by andybalholm** [comment]
Retrying is only safe when the request is idempotent (e.g. GET, not POST). Retrying GET and HEAD requests has been implemented in net/http already (https://github.com/golang/go/commit/5dd372bd1e70949a432d9b7b8b021d13abf584d1).

**Comment by elico** [comment]
@andybalholm What I did was to not use a RoundTripper but a simple http.Client.
This gives some "overhead" but makes it so the requests are making it 100% of the time.

**Comment by andybalholm** [comment]
A Client follows redirects and such. That would be a pretty strange behavior for a proxy.

**Comment by elico** [comment]
@andybalholm It's pretty easy to resolve..
Snippet:
```
func noRedirect(req *http.Request, via []*http.Request) error {
        return errors.New("REDIRECT!!!")
}
func createHTTPClient() *http.Client {
        client := &http.Client{
                Transport: &http.Transport{
                        MaxIdleConnsPerHost: MaxIdleConnections,
                },
                Timeout:       time.Duration(RequestTimeout) * time.Second,
                CheckRedirect: noRedirect,
        }

        return client
}
...
        start := time.Now()
        var err error
        var resp *http.Response

        for retry := 0; retry < retries; retry++ {
                if roundtripper {
                        resp, err = tr.RoundTrip(r)
                } else {
                        resp, err = httpClient.Do(r)
                }
                if err == nil {
                        break
                } else {
                        time.Sleep(1 << uint(retry) * time.Second)
                }
        }
        switch {
        case err != nil && strings.Contains(err.Error(), "REDIRECT!!!"):
                redirect = true
                _ = redirect
        case err != nil:
                switch {
                case strings.Contains(err.Error(), "REDIRECT!!!"):

                default:
                        if verbose {
                                L.Println(r.URL, " ", err.Error())
                        }
                        http.Error(w, err.Error(), http.StatusInternalServerError)
                        return
                }
        default:

        }

        CopyHeader(w, resp)
        w.WriteHeader(resp.StatusCode)
...
```

**Comment by elico** [comment]
I am testing the latest code and it seems for now to be pretty stable.
Any ideas on a way to verify if one of the commits did well with this bug?

**Comment by andybalholm** [comment]
I changed the default setting for close-idle-connections to 1 minute in https://github.com/andybalholm/redwood/commit/014d9508246d855690d08a283fabd9860273a64e

Is that what made the difference?

**Comment by elico** [comment]
@andybalholm I believe so.

**Comment by elico** [comment]
I think that the soution is satisfying.
