### ISSUE TITLE
script to assign ACL files to specific users before the acl file is read

### ISSUE THREAD

**Issue by Dallas041998** [andybalholm/redwood#92]
Looking for example script to be able to seperate users into seperate acl action files to be better able to whitelist for each specific user...
any help would be appreciated...
have tried multiple ways but still coming up empty handed

Thanks

**Comment by andybalholm** [comment]
Which ACLs are assigned to which user doesn't depend on which files they are in. The ACLs are one big list, applied in the order they are loaded.

**Comment by andybalholm** [comment]
Assuming you have a category named `restricted-sites`, with a default action of `block`:

```
acl special-users user-name andy
acl special-users user-ip 10.1.1.7
allow restricted-sites special-users
```

This would allow access to the restricted-sites category only to the user at IP address 10.1.1.7 and a user who authenticates as "andy".

**Comment by Dallas041998** [comment]
Thanks... that helps to clarify my questions...
ill play with that and see how it performs...
